<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CheckoutPostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' =>'required|min:6',
            'email' =>'required|email|unique:customers',
            'password' =>'required|min:6|max:20',
            'address' =>'required',
            'phone' =>'required|numeric|min:100000000|max:99999999999'
            //
        ];
    }

    public function messages()
    {
//        return parent::messages[]
//            'phone.min' =>'ít nhất 10 sô',
//        ); // TODO: Change the autogenerated stub
    }
}
